; Generated by AutoGUI 2.6.2
full_command_line := DllCall("GetCommandLine", "str")

if not (A_IsAdmin or RegExMatch(full_command_line, " /restart(?!\S)"))
{
    try
    {
        if A_IsCompiled
            Run *RunAs "%A_ScriptFullPath%" /restart
        else
            Run *RunAs "%A_AhkPath%" /restart "%A_ScriptFullPath%"
    }
    ExitApp
}



#SingleInstance Force
#NoEnv
#Include installFiles.ahk
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui -MinimizeBox ;+AlwaysOnTop
Gui Color, White
Gui Add, Text, x8 y319 w517 h2 +0x10
Gui Add, Button, hWndhInstaller vinstaller ginstaller x301 y333 w80 h23, Installer
Gui Add, Button, hWndhAnnuler vannuler gannuler x392 y332 w104 h23 +Default, &Annuler l'intallation
Gui Font, s22, Courier New
Gui Add, Text, x40 y10 w450 h23 +0x200, Initial_Language INSTALLER
Gui Font
Gui Add, Text, x15 y47 w499 h2 +0x10
Gui Add, Progress, hWndhProgBar vProgBar x71 y57 w335 h20 -Smooth
Gui Add, GroupBox, x14 y83 w508 h227, INSTALLATIONS
Gui Font, s15, Courier New
Gui Add, Text, x119 y108 w228 h23 +0x200, NODE.js 
Gui Font
Gui Font, s15, Courier New
Gui Add, Text, x121 y153 w228 h23 +0x200, AUTOHOTKEY 
Gui Font
Gui Font, s15, Courier New
Gui Add, Text, x119 y198 w228 h23 +0x200, NOTEPAD++
Gui Font
Gui Font, s15, Courier New
Gui Add, Text, x119 y239 w228 h23 +0x200, Initial_Language
Gui Font
;Gui Add, Picture, x12 y-8 w74 h55, E:\CSIE\CODES\JC\uc\icons\il.ico
;Gui Add, Picture, x448 y-8 w76 h54, E:\CSIE\CODES\JC\uc\icons\il.ico
Gui Add, Picture, x319 y105 w183 h168, .\icons\il.ico
Gui Font, s16 c0x8080FF, Arial
Gui Add, Text, vOkNode gOkNode x63 y108 w45 h23 +0x200, X
Gui Font
Gui Font, s16 c0x8080FF, Arial
Gui Add, Text, vOkAhk gOkAhk x63 y150 w45 h23 +0x200, X
Gui Font
Gui Font, s16 c0x8080FF, Arial
Gui Add, Text, vOkNotepad gOkNotepad x65 y197 w45 h23 +0x200, X
Gui Font
Gui Font, s16 c0x8080FF, Arial
Gui Add, Text, vOkIl gOkIl x65 y240 w45 h23 +0x200, X
Gui Font
Gui Font, c0xFF0000
Gui Add, Text, x27 y279 w382 h23, Toutes ces programmes sont requise pour l'installation du Langage Initial
Gui Font
Gui Add, Picture, x5 y327 w41 h33, .\icons\photostudio_1597212448959.png
Gui Add, Text, x51 y324 w160 h40 +0x200, Ether Solutions, CopyRight 2020
Gui Add, Text, x5 y55 w57 h23 +0x200, Version 1.0
Gui Add, Text, x417 y55 w109 h23 +0x200, C:\Initial_Language\

Gui Show, w535 h364, installation Initial_Language
Return

installer(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "", intall:=true) {
;OkNode()s
    ;progBar(50)
    ;installationsChecker()
    installationsChecker(autoHotKey, autoHotKeyLib, ahkArch, nppArch, nodeJs, notePad, tmpIl, nppAppData, ilRuner)
    ;MsgBox %autoHotKey%
    start:
    if(!autoHotKey){
        try {
            RunWait % ".\installations\AutoHotkey_1.exe"
            GuiControl, Text, OkAhk , OK
            FileCopy, .\libs\*.ahk, %A_ProgramFiles%\Autohotkey\Lib\
            progBar(20)
        }
        catch err
        {
            ;MsgBox, The window does not exist.
            MsgBox, 262197, installation rejetter, Vous avez rejetter l'installation de AutoHotKey le programme ne poura pas installer si tout les ellements necessaires ne seront pas installer
            IfMsgBox, Retry
                goto start
        }
    }
        
    if(!autoHotKeyLib){
        if(ahkArch==32){
            FileCreateDir, C:\Program Files (x86)\AutoHotkey\Lib
            FileCopy, .\libs\*.ahk, C:\Program Files (x86)\Autohotkey\Lib\
            progBar(5)
        } else if(ahkArch==64){
            FileCreateDir, %A_ProgramFiles%\AutoHotkey\Lib
            FileCopy, .\libs\*.ahk, %A_ProgramFiles%\Autohotkey\Lib\
            progBar(5)
        }
    }
    if(!nodeJs){
        try
        {
            RunWait % ".\installations\node_v12.msi"
            GuiControl, Text, OkNode , OK
            progBar(20)
        } 
        catch err
        {
            ;MsgBox, The window does not exist.
            MsgBox, 262197, installation rejetter, Vous avez rejetter l'installation de NodeJs le programme ne poura pas installer si tout les ellements necessaires ne seront pas installer
            IfMsgBox, Retry
                goto start
        }
        
    }
    if(!notePad){
        try {
            RunWait % ".\installations\npp_7_8_2.exe"
            GuiControl, Text, OkNotepad , OK
            progBar(20)
            if(nppArch==32){
                FileCopyDir, .\installations\configs\plugins , C:\Program Files (x86)\Notepad++\plugins, 1
                FileCopy, .\installations\configs\il.xml , C:\Program Files (x86)\Notepad++\autoCompletion\, 1
                progBar(5)
            } else if(nppArch==64){
                FileCopyDir, .\installations\configs\plugins , %A_ProgramFiles%\Notepad++\plugins, 1
                FileCopy, .\installations\configs\il.xml , %A_ProgramFiles%\Notepad++\autoCompletion\, 1
                progBar(5)
            }
        }
        catch err
        {
            MsgBox, 262197, installation rejetter, Vous avez rejetter l'installation de NotePad++ le programme ne poura pas installer si tout les ellements necessaires ne seront pas installer
            IfMsgBox, Retry
                goto start
        }
    } else {
        progBar(20)
        if(nppArch==32){
            FileCopyDir, .\installations\configs\plugins , C:\Program Files (x86)\Notepad++\plugins, 1
            FileCopy, .\installations\configs\il.xml , C:\Program Files (x86)\Notepad++\autoCompletion\, 1
            progBar(5)
        } else if(nppArch==64){
            FileCopyDir, .\installations\configs\plugins , %A_ProgramFiles%\Notepad++\plugins, 1
            FileCopy, .\installations\configs\il.xml , %A_ProgramFiles%\Notepad++\autoCompletion\, 1
            progBar(5)
        }
    }
    ;INSTALLATION INITIAT LANGUAGE
    if(autoHotKey && autoHotKeyLib && nodeJs && notePad ){
        install_IL()
    }
    if(!tmpIl){
        FileCreateDir, C:\Users\%A_UserName%\Documents\temps_IL
    } 
    if(!nppAppData){
        FileCreateDir, %A_AppData%\Notepad++old
        FileCopyDir, %A_AppData%\Notepad++\ , %A_AppData%\notepad++old , 1
        FileCopyDir, .\installations\configs\Notepad++ , %A_AppData%\Notepad++ , 1
        progBar(5)
    }
}

annuler(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    ExitApp
}

progBar(prcnt) {
    GuiControl,, ProgBar , +%prcnt%
    ;GuiControl,, MyProgress, 50
}

OkNode() {
    GuiControl, Text, OkNode , OK
}

OkAhk() {
    GuiControl, Text, OkAhk , OK
}

OkNotepad() {
    GuiControl, Text, OkNotepad , OK
}

OkIl() {
    GuiControl, Text, OkIl , OK
}
;------------------------------------------
;MsgBox prince
autoHotKey := false
autoHotKeyLib := false
ahkArch := 32
nppArch := 32
nodeJs := false
notePad := false
tmpIl := false
nppAppData := false
ilRuner := false

install_IL(){
    ;installationsChecker(autoHotKey, autoHotKeyLib, ahkArch, nodeJs, notePad, tmpIl, nppAppData)
    if(!ilRuner){
        FileCreateDir, c:\Initial_Language
        progBar(3)
        FileCopyDir, .\doc, c:\Initial_Language\doc, 1
        FileCopyDir, .\configs, c:\Initial_Language\configs, 1
        progBar(3)
        FileCopyDir, .\exemples, c:\Initial_Language\exemples, 1
        progBar(3)
        FileCopyDir, .\icons, c:\Initial_Language\icons, 1
        progBar(3)
        FileCopyDir, .\modules, c:\Initial_Language\modules, 1
        progBar(3)
        FileCopyDir, .\tmps, c:\Initial_Language\tmps, 1
        progBar(3)
        FileCopyDir, .\exemples, c:\Initial_Language\exemples, 1
        progBar(3)
        FileCopy, .\logs.log, c:\Initial_Language\, 1
        progBar(3)
        FileCopy, .\template.txt, c:\Initial_Language\, 1
        FileCopy, .\unintaller.exe, c:\Initial_Language\, 1
        progBar(3)
        ;--------------------------------------------------
        
        ;[HKEY_CLASSES_ROOT\initial.language\Shell\compiler]
        ;@="Compiler le programme"
        ;RegWrite, REG_SZ, HKEY_CLASSES_ROOT\initial.language\Shell\compiler, , Compiler le programmess
        #Include register.ahk
        
        ;--------------------------------------------------
        OkIl()
        GuiControl, Disable, installer
        GuiControl, Text, annuler , Terminer!
        progBar(3)
        
        IfNotExist, C:\Program Files\AutoHotkey\SciTE\SciTE.exe
        {
            MsgBox, 262180, editeur AHK, Voulez-vous installer l'IDE AutoHotKey ?
            IfMsgBox, Yes
            {
                try {
                    RunWait, .\installations\SciTE4AHK300601_Install.exe
                } 
                    
            }
        } else
        {
            MsgBox, 262180, INSTALLATION TERMINER, TOUT LES PROGRAMMES NECESSAIRE SONT INSTALLER.`nVOUS ETE A PRESENT PRET A LANCER.`n`nVOULEZ-VOUS LANCER ?
            IfMsgBox Yes
            {
                path := "C:\Initial_Language\exemples\controls.il"
                if(nppArch==64){
                    run, %A_ProgramFiles%\Notepad++\notepad++.exe %path%
                    ExitApp, 1
                } else
                    run, C:\Program Files (x86)\Notepad++\notepad++.exe %path%
            }
        }
    }
    
}

;------------------------------------------
GuiEscape:
GuiClose:
    ExitApp
return





